### ISSUE TITLE
A serious bug in date calculation.

### ISSUE THREAD

**Issue by code-yeongyu** [Gijuno/ITP-TimeTravel-macos#1]
Hi. Thank you for this useful project, and I really appreciate about what you've done.

However, I found a serious bug in date calculation. I work as ITP and started my duty at 1/18/2024, but it's saying that the end date of mine is 2026/11/17.

<img width="218" alt="image" src="https://github.com/Gijuno/ITP-TimeTravel-macos/assets/11153873/9630f67a-56f7-4f2c-9204-b33e2f9c8f4d">

I am 22 years old (21 in international age), and IT'S ABOUT TO BE 25, AFTER I END MY DUTY. THIS CAN'T BE TRUE. It's making me really sad.

I believe that this is a serious bug since it makes me depressed. I hope you to fix this bug soon, and I'll be waiting for your reply. Thank you.

**Comment by Gijuno** [comment]
Hi. Thank you for your interest in my project
I've gone over the bug you found very carefully and have found a workaround.
I found out that if you don't eat Tteokguk, you don't age.
(NASA can't stop calling me)

**Comment by code-yeongyu** [comment]
> I found out that if you don't eat Tteokguk, you don't age.
> (NASA can't stop calling me)

That makes sense. I'll always be careful when my Mom tells me to eat tteokguk on New Year's.

Thank you for your hot fix and have a good day as an agent. I'll close this issue.
